lev/src/lev_stubs.c
ps-id: 2413fca2-c026-4efb-bc24-0aad78db2f81
=> fix(lev): use correct signals

lev-fiber/src/lev_fiber.ml
we'll have to maintain for non windows as well
ps-id: 351a32a9-58c0-43cf-987e-7fbde0b1d9f1
=> refactor(lev-fiber): process table

lev/test/dune, lev/test/lev_tests_signals.ml
ps-id: be7625e9-8ead-4a99-bfaf-188fe2600d6c
=> test(lev): simple signal handling test

lev/src/lev.mli
ps-id: 4b9743d8-cfe1-40fa-8bfa-278cdd071c23
=> feature(lev): empty flags

lev-fiber/test/process.ml
ps-id: 834d8c3b-5131-46a5-b100-dbf0d99fbd42
=> test(lev-fiber): create process inside loop

lev/src/lev.ml, lev/src/lev.mli, lev/src/lev_stubs.c
ps-id: 4546e1f1-8faf-4eb8-80bd-77034663b0fb
=> feature(lev): Loop.{ref,unref}

lev/test/lev_tests.ml
ps-id: c30e4c08-ff61-44ae-afcc-f73f855f5c1f
=> test(lev): unref

lev/src/lev.ml, lev/src/lev.mli, lev/src/lev_stubs.c, lev/test/lev_tests.ml
ps-id: c686b952-d0e6-42c5-bdbb-f5d823b36718
=> feature(lev): test for default loop

lev/src/lev.ml, lev/src/lev.mli, lev/src/lev_stubs.c
ps-id: 97f9c7f3-ca71-4445-9364-9a7d0fbb4c76
=> feature(lev): signal feeding primitives

dune-project, lev-fiber-csexp.opam
ps-id: 83a478b2-ffbe-4b72-bd3b-1f6fc17a2f4b
=> chore: fiver lev-fiber-csexp metadata

.github/workflows/workflow.yml
ps-id: cfae84cd-0c9e-4b45-90af-fc2a90a1d5bb
=> chore: test lev and lev-fiber in ci

lev-fiber/src/lev_fiber.ml, lev-fiber/src/lev_fiber.mli, lev-fiber/test/reader_writer.ml, lev/test/lev_tests.ml
we only reap processes the user asked us to
ps-id: 9a55bdcf-882b-45af-a5f6-c96a050c676f
=> fix(lev-fiber): safe process reaping

lev-fiber/src/lev_fiber.ml
ps-id: 07fcce2f-ccd0-41dd-85ad-0d21ff75c1ae
=> fix(lev-fiber): windows support

lev-fiber-csexp/test/lev_fiber_csexp_rpc_tests.ml, lev-fiber/bench/ping_pong.ml, lev-fiber/src/lev_fiber.ml, lev-fiber/src/lev_fiber.mli, lev-fiber/test/lev_fiber_threads.ml, lev-fiber/test/process.ml, lev-fiber/test/reader_writer.ml, lev-fiber/test/sockets.ml, lev-fiber/test/timers.ml, lev/src/lev.mli
create the event loop ourselves and make sure Nosigprocmask is set
ps-id: 0f78edad-b9be-407f-8f6a-6101f49e1b88
=> feature(lev-fiber): simplify sigprocmask safety

lev-fiber-csexp/src/lev_fiber_csexp.ml, lev-fiber-csexp/test/lev_fiber_csexp_rpc_tests.ml, lev-fiber/src/lev_fiber.ml, lev-fiber/src/lev_fiber.mli, lev-fiber/test/sockets.ml
raise BADF when accessing closed fd
ps-id: 3734be21-64f8-4162-9dc9-dfe2ee4974b4
=> fix(lev-fiber): closed fd handling

lev-fiber-csexp/test/lev_fiber_csexp_rpc_tests.ml, lev-fiber/src/lev_fiber.ml
ps-id: d9d4bd24-24b8-4a13-804a-f03cf610c22f
=> test(lev-fiber-csexp): use tcp on windows

lev-fiber/test/timers.ml
ps-id: 011ca858-b670-413a-be4a-14735817b00b
=> test(lev-fiber): remove flaky test

lev-fiber/src/util/channel.ml, lev-fiber/src/util/channel.mli
ps-id: fcf1f2f4-b11c-42dd-b9bb-a29523f3ab08
=> refactor(lev-fiber): remove dead code

lev-fiber/src/lev_fiber.ml
only increment ref count after task is successfully created
ps-id: 6ca76ce7-a598-4101-8cad-43ba8b967240
=> refactor(lev-fiber): safer ref count

lev-fiber/src/lev_fiber.ml
ps-id: d0302a10-2fa0-4014-b9a4-693dc605f987
=> refactor: process reapign in one place

lev-fiber/src/lev_fiber.ml, lev-fiber/src/lev_fiber.mli, lev-fiber/test/lev_fiber_threads.ml
ps-id: 61d4635a-8d86-4424-80bc-8b2734604eba
=> refactor: handle stopped threads better

.github/workflows/workflow.yml, lev-fiber/test/util/dune
ps-id: 24d7f0f0-9441-4b57-80b9-1b1ad02c8470
=> test: try workaround for ppx_expect

lev/test/dune
ps-id: a53d8d9d-e5cc-4a18-9610-7731fa44a1cb
=> test: improve enabled if on windows

lev-fiber/test/sockets.ml
ps-id: 78e6fe35-b5db-4a77-8db9-77dc0894512e
=> test(lev-fiber): fix socket test on windows

lev/test/dune
ps-id: c854b435-94b3-4919-a538-633c9dc6eeb6
=> test: correctly disable tests on windows

lev/test/lev_tests.ml
ps-id: 712bbfe6-45bb-4c72-a14d-30f35f3c8a82
=> test(lev): fix pipes test on windows

lev/test/lev_tests.ml, lev/test/lev_tests_unix.ml
ps-id: 75241e6e-416a-47e6-a919-4540716cbf3d
=> test(lev): move non-windows test

lev/test/dune, lev/test/sockets.ml
ps-id: b5f4ec62-d2e3-49c6-88ff-60cbac3d9bfa
=> test(lev): listening on tcp socket

lev/src/lev_stubs.c
ps-id: 589cdf54-7a86-4975-829c-9ce51222308d
=> fix(lev): use correct fd on windows

lev-fiber/test/sockets.ml
use tcp tockets correctly
ps-id: 3152aab0-9ed3-4d57-9fc5-4449817380c4
=> test(lev-fiber): fix sockets tests on windows

lev-fiber/test/sockets.ml, lev/test/sockets.ml
windows...
ps-id: b7a52d4e-9b50-4a0c-9711-c0761b37d099
=> test: use loopback for tcp

lev/test/lev_tests.ml
ps-id: 4dac0569-9ee9-42bc-9591-3dcd602db8da
=> test(lev): 0 timers don't work on windows

lev-fiber-csexp/test/lev_fiber_csexp_rpc_tests.ml
ps-id: 004ec260-040c-4bc2-bbc0-2707170d8e69
=> test(lev-fiber-csexp): windows

lev-fiber/src/lev_fiber.ml
ps-id: baf984d9-8e51-42fd-b851-823b6164504a
=> fix(lev-fiber): handle EWOULDBLOCK on windows

lev-fiber/src/lev_fiber.ml
ps-id: fab3a289-6a0b-4bd9-8fa9-89b3485633da
=> refactor(lev-fiber): EISCONN only on windows

lev-fiber/src/lev_fiber.mli
ps-id: a34563a4-51c9-4193-9e3e-dba1b85c34da
=> chore: document [fd_exn]

lev-fiber/src/lev_fiber.ml
ps-id: a266c428-d657-4094-b7a4-07081c1a50b7
=> refactor: move close_fd close to caller

lev-fiber/src/lev_fiber.ml
The underlying [Fd.t] will raise anyway
ps-id: c61bae64-55ae-4da8-ad57-66de5fa94644
=> fix: stop raising in [Io.fd]

lev-fiber-csexp/src/lev_fiber_csexp.ml, lev-fiber-csexp/src/lev_fiber_csexp.mli, lev-fiber-csexp/test/lev_fiber_csexp_rpc_tests.ml
ps-id: 91dca1fc-9074-4be4-8f00-e4f7e74407d5
=> refactor(lev-fiber-csexp): split close/write

lev-fiber/src/lev_fiber.mli
ps-id: fc1cc750-1eeb-4298-a0e6-61a62e547365
=> chore: document Lev_fiber.Io.close

lev-fiber/test/reader_writer.ml
ps-id: bcd8fb4a-3a4d-47bd-b22f-017732d7a36e
=> test(lev-fiber): writing to closed pipes

lev-fiber/src/lev_fiber.ml
ps-id: 1b2c5f41-4fbe-4c99-894b-1e8f9f002cc7
=> fix(lev-fiber): stop handling EBADF

lev/test/lev_tests_unix.ml
ps-id: d3bb9571-ce93-4110-96fc-7cb7be5f153b
=> test(lev): pipe closed tests

lev/test/lev_tests_unix.ml
ps-id: db3dfa1c-16d4-44ec-a740-c37519bb151e
=> test(lev): sigpipe

lev/test/lev_tests_unix.ml
ps-id: f2d52224-156d-44e6-a748-2ad18bb9f16b
=> test(lev): refactor existing tests

lev-fiber/src/lev_fiber.ml
ps-id: 53df3f8d-15c5-4d61-85e9-130dac5317c9
=> fix(lev-fiber): purify with_{read,write}

lev-fiber/src/lev_fiber.ml
ps-id: 377d0fa7-17b7-4813-8f3b-002944832314
=> fix(lev-fiber): check no concurrent read/write

lev-fiber/src/lev_fiber.ml
ps-id: 481a7673-6a9e-4105-b8dd-0c02f437558e
=> refactor(lev-fiber): add some better debugging

lev-fiber/src/lev_fiber.ml
ps-id: d076249e-63dd-46a0-b50d-85a822aae1ea
=> fix(lev-fiber): more source printing

lev-fiber/src/lev_fiber.ml
ps-id: 3d7defba-494d-47dc-a7fa-2d0b16196762
=> feature(lev-fiber): introduce [LEV_DEBUG]

lev-fiber/test/basic.ml
ps-id: 74649c82-3b09-4df1-a28e-ab0598cb3f0b
=> test(lev-fiber): exception/scheduling tests

lev-fiber/src/lev_fiber.ml, lev-fiber/src/lev_fiber.mli, lev-fiber/test/basic.ml, lev-fiber/test/lev_fiber_threads.ml
ps-id: 412db637-909b-4199-94d8-2855501150c2
=> fix(lev-fiber): move deadlock to common error type

lev-fiber/src/lev_fiber.ml, lev-fiber/test/reader_writer.ml
ps-id: 22d70863-1fbe-4f10-9460-1110245a7088
=> refactor: improve write failure messages

lev-fiber/test/reader_writer.ml
ps-id: 4a0631b8-5b8e-4785-9f0d-f39b07adb54e
=> chore: make fmt

lev/vendor/ev.c, lev/vendor/ev_iouring.c
ps-id: 8a4edbb0-f91c-4567-8960-50c640fc7f78
=> chore(lev): update libev

.ocamlformat
=> chore: update ocamlformat

.github/workflows/workflow.yml, flake.lock, flake.nix
=> chore: add nix files

.github/workflows/workflow.yml
=> chore: add lev-fiber-csexp to CI

flake.nix
=> chore: add ccls to flake

.github/workflows/workflow.yml, README.md
The tests are successful anyway, we don't need to allow failure.
=> coverage: allow job to fail

lev-fiber/src/lev_fiber.ml
=> fix(lev-fiber): fd leak when running scheduler

flake.lock
=> chore: update flakes

lev-fiber/src/lev_fiber.ml
=> chore(lev-fiber): list stdune modules

.github/workflows/workflow.yml, flake.lock, flake.nix, lev-fiber-csexp/test/dune, lev-fiber/test/dune, lev-fiber/test/util/dune, lev/test/dune
=> chore: update to 5.x
